jQuery(function($){'use strict',$(function(){$('.carousel').carousel({interval:5000});});$('.accordion-toggle').on('click',function(){$(this).closest('.panel-group').children().each(function(){$(this).find('>.panel-heading').removeClass('active');});$(this).closest('.panel-heading').toggleClass('active');});new WOW().init();$(window).load(function(){'use strict';var $portfolio_selectors=$('.portfolio-filter >li>a');var $portfolio=$('.portfolio-items');$portfolio.isotope({itemSelector:'.portfolio-item',layoutMode:'fitRows'});$portfolio_selectors.on('click',function(){$portfolio_selectors.removeClass('active');$(this).addClass('active');var selector=$(this).attr('data-filter');$portfolio.isotope({filter:selector});return false;});});var form=$('#main-contact-form');form.submit(function(event){event.preventDefault();var form_status=$('<div class="form_status"></div>');$.ajax({url:$(this).attr('action'),beforeSend:function(){form.prepend(form_status.html('<p><i class="fa fa-spinner fa-spin"></i> Email is sending...</p>').fadeIn());}}).done(function(data){form_status.html('<p class="text-success">'+data.message+'</p>').delay(3000).fadeOut();});});$('.gototop').click(function(event){event.preventDefault();$('html, body').animate({scrollTop:$("body").offset().top},500);});$("a[rel^='prettyPhoto']").prettyPhoto({social_tools:false});$(window).scroll(function(){if(($(this).scrollTop()>0)&&($(window).width()>767)){$("#header").addClass("fixed-header-on");}else{$("#header").removeClass("fixed-header-on");}});$(window).load(function(){if(($(this).scrollTop()>0)&&($(window).width()>767)){$("#header").addClass("fixed-header-on");}else{$("#header").removeClass("fixed-header-on");}
if($(window).width()>991)
{$('.pull-down').each(function(){$(this).css('margin-top',$(this).parent().height()-$(this).height())});}
else
{$('.pull-down').each(function(){$(this).css('margin-top','0px')});}});$(window).bind('resize',function(){if($(window).width()>991)
{$('.pull-down').each(function(){$(this).css('margin-top',$(this).parent().height()-$(this).height())});}
else
{$('.pull-down').each(function(){$(this).css('margin-top','25px')});$('footer').css('padding-bottom','0px');}});if($(".scrollspy").length>0){$("body").addClass("scroll-spy");$('body').scrollspy({target:'.scrollspy',offset:150});}
if($(".smooth-scroll").length>0){$('.smooth-scroll a[href*=#]:not([href=#]), a[href*=#]:not([href=#]).smooth-scroll').click(function(){if(location.pathname.replace(/^\//,'')==this.pathname.replace(/^\//,'')&&location.hostname==this.hostname){var target=$(this.hash);target=target.length?target:$('[name='+this.hash.slice(1)+']');if(target.length){$('html,body').animate({scrollTop:target.offset().top-55},1000);if($(window).width()<767)
{$(".navbar-collapse").collapse('hide');}
mySlidebars.slidebars.close();return false;}}});}});